## Numpy array and basics


In [34]:
import numpy as np

Creating array from list

In [35]:
arr_1d = np.array([1, 2, 3])
print("1D array:",arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n",arr_2d)

1D array: [1 2 3]
2D array:
 [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [36]:
py_list=[1,2,3]
print("Python List Multiplication ",py_list*2) 
np_array = np.array([1,2,3]) # element-wise operations
print("Numpy Array Multiplication ",np_array*2)

import time
start = time.time()
py_list = list(i*2 for i in range(1000000))
print ("Python List Time: ", time.time() - start)
start = time.time()
np_array = np.arange(1000000)*2
print ("Numpy Array Time: ", time.time() - start)

Python List Multiplication  [1, 2, 3, 1, 2, 3]
Numpy Array Multiplication  [2 4 6]
Python List Time:  0.05308842658996582
Numpy Array Time:  0.003244161605834961


### creating array from scratch

In [37]:
zeros=np.zeros((3,4))
print("Zeros Array:\n",zeros)

ones=np.ones((3,4))
print("Ones Array:\n",ones)

full=np.full((2,2),7)
print("Full Array:\n",full)

random = np.random.random((2,3))
print("Random Array:\n",random)

sequence = np.arange(0,10,2)
print("Sequence Array:",sequence)



Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array:
 [[7 7]
 [7 7]]
Random Array:
 [[0.33070581 0.59917711 0.97987815]
 [0.42322054 0.76190257 0.46593909]]
Sequence Array: [0 2 4 6 8]


### Vector, Matrix and Tensor

In [38]:
vector=np.array([1,2,3])
print("Vector:",vector)

matrix=np.array([[1,2,3],[4,5,6]])
print("Matrix:\n",matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("Tensor:\n",tensor)

Vector: [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties


In [ ]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("Shape",arr.shape)
print("Dimensions",arr.ndim)
print("Size",arr.size)
print("Data Type",arr.dtype)
#Float data Types
arr=np.array([[1,2,3],
              [4,5,6.8]])
print("Shape",arr.shape)
print("Dimensions",arr.ndim)
print("Size",arr.size)
print("Data Type",arr.dtype)

Shape (2, 3)
Dimensions 2
Size 6
Data Type int64
Shape (2, 3)
Dimensions 2
Size 6
Data Type float64


### Array Reshaping

In [40]:
arr=np.arange(12)
print("Original Array:",arr)

reshaped=arr.reshape((3,4))
print("\n Reshaped Array (3x4):\n",reshaped)

# flatten (returns copy)
flattened=reshaped.flatten()
print("\n Flattened Array:",flattened)

# ravel (returns view , instead of copy)
raveled=reshaped.ravel()
print("\n Raveled Array:",raveled)

#Transpose
transpose =reshaped.T
print("\n Transposed Array:\n",transpose)


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
