## Numpy Array operations

In [4]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing:",arr[2:7])
print("With Step",arr[1:8:2])
print("Negative Indexing:",arr[-3])

Basic Slicing: [3 4 5 6 7]
With Step [2 4 6 8]
Negative Indexing: 8


### 2D Array Operation

In [10]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific element:",arr_2d[1,2])
print("Entire Row:",arr_2d[1])
print("Entire Column:",arr_2d[:,1])



Specific element: 6
Entire Row: [4 5 6]
Entire Column: [2 5 8]


## Sorting

In [16]:
unsorted=np.array([3,1,4,1,5,9,2,6])
print("Sorted array:",np.sort(unsorted))

arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column\n",np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2D array by row\n",np.sort(arr_2d_unsorted,axis=1))


Sorted array: [1 1 2 3 4 5 6 9]
Sorted 2D array by column
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row
 [[1 3]
 [1 2]
 [2 3]]


## Filter

In [18]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_numbrs=numbers[numbers%2==0]
print("Even Numbers:",even_numbrs)


Even Numbers: [ 2  4  6  8 10]


## Filter with mask

In [20]:
mask=numbers>5
print("Numbers greater than 5:",numbers[mask])
print("Numbers greater than 5 (inline):",numbers[numbers>5])

Numbers greater than 5: [ 6  7  8  9 10]
Numbers greater than 5 (inline): [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [24]:
indices=[0,2,4]
print("Elements at indices 0,2,4:",numbers[indices])

where_indices=np.where(numbers>5)
print("Indices where numbers >5:",where_indices)
print("Elements greater than 5 using where:",numbers[where_indices])

Elements at indices 0,2,4: [1 3 5]
Indices where numbers >5: (array([5, 6, 7, 8, 9]),)
Elements greater than 5 using where: [ 6  7  8  9 10]


In [33]:
conditions_array=np.where(numbers>5,numbers*2,numbers)
print(conditions_array)
# If condition is true, multiply by 2 else keep same
# Condition , First Parameter if true , Second Parameter if false
conditions_array=np.where(numbers>5,"True","False")
print(conditions_array)

[ 1  2  3  4  5 12 14 16 18 20]
['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


### Adding and Removing Data

In [35]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=arr1+arr2
print("Addition:",arr3)
combined=np.concatenate((arr1,arr2,arr3))
print("Concatenation:",combined)

Addition: [5 7 9]
Concatenation: [1 2 3 4 5 6 5 7 9]


### Array compatibilty operations

In [38]:
a=np.array([1,2,3])
b=np.array([4,5,6,7])
c=np.array([7,8,9])

print("Compatibility shapes(a,b)",a.shape==b.shape )
print("Compatibility shapes(a,c)",a.shape==c.shape )

Compatibility shapes(a,b) False
Compatibility shapes(a,c) True


In [43]:
original=np.array([[1,2],[3,4]])
print("Original Array:\n",original)
new_row=np.array([[5,6]])
print("New Row to add:\n",new_row)
with_new_row=np.vstack((original,new_row))
print("After adding new row with vstack:\n",with_new_row)

new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print("After adding new column with hstack:\n",with_new_col)

Original Array:
 [[1 2]
 [3 4]]
New Row to add:
 [[5 6]]
After adding new row with vstack:
 [[1 2]
 [3 4]
 [5 6]]
After adding new column with hstack:
 [[1 2 7]
 [3 4 8]]


### Deleting 

In [47]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2)
print("Array after deleting index 2:",deleted)

arr_2d=np.array([[1,2,3],
                 [4,5,6],
                [7,8,9]])
deleted_row=np.delete(arr_2d,1,axis=0)
print("2D Array after deleting row 1:\n",deleted_row)
deleted_col=np.delete(arr_2d,0,axis=1)
print("2D Array after deleting column 0:\n",deleted_col)
specfic_elem=np.delete(arr_2d,4)
print("2D Array after deleting element at index 4 (flattened):\n",specfic_elem)

Array after deleting index 2: [1 2 4 5]
2D Array after deleting row 1:
 [[1 2 3]
 [7 8 9]]
2D Array after deleting column 0:
 [[2 3]
 [5 6]
 [8 9]]
2D Array after deleting element at index 4 (flattened):
 [1 2 3 4 6 7 8 9]
